language: java
jdk:
- openjdk8
deploy:
  provider: releases
  api_key:
      secure: VBScpk/ENQTMQeCpl1zOKhiR0VoMro2nBJLD5dZeNV0dpgvbm5qGJMwW/wan7tH/+PU8zkTabA/2AXe+LX/2+I7FGlcB7laXceohr9tdba3bwbdPuIonERMm5q2JPSbMo7L9zFWl+KtIKoXG2v0DB1rNvE51T7LHSLqNVd4MkpSGnZMSZt9ga68CFP0GxGgU/u/BjqFmQoezZmVv27KIUs7+GdaNwE5V4OP3CD2N/GK/jC/saUVersFtXxh6PEANk7S2FbiSjY2+ud3n3myHSYDnXJTA1TX2Gr4YCc9CqC6T9zr/+6eMPvOpR/svXYGVsMxDDJCpz2LuIvkgVErlrlEw12OFaLIi4u8M9rFOSPJMOAjmN1IEltQ8RU20Hr21PGp/agFt2pri8kgWV/d6yGUOAMOYPuMGVTrBB0m/so+iGdKIJHPbNbjvy8aWbU/uGCzluj4wRghJOXfEluCVgGEJRMmpwYUdORqZg2JecCrX618h3q9LFry9/gQWQ+i+X8HUJCUp9uj5DDsvGAXnFBftVda7amwOH3ruazGW9M8Gvl78bBrzYU3haiL4yBbrpcJYV4BjHy5h27tAosaoO9LaMxHP8+D41TScbMmI+h2Y3yD8F6QteGi++gleTLjHMmgI1icSR0mizH7Xw0a85t18Kp1CDgcLu6Ux6UOHfiI=

  file: target/*.jar
  skip_cleanup: true
  on:
    repo: jbharter/Syndicate
    tags: true
