language: java
jdk:
- openjdk8
deploy:
  provider: releases
  api_key:
    secure: OVABRK5JFE1Bn8RecfGM0H9nd7/sKCsReUO1NDqMQCZJsaf2E+9YE4D/862MXPe0PPsWT6/0EqiAK5pYIEy+UPdtUyzpEb/ZpjFjuSBgdSKvyEiSny59fmeXNRinMGpvzYJBg69sEN8uHTsjPvp6/i1I9EW8hU1MnkC1lFm5Lx/M0eSePIivFhfnv+v5L7hjM4jtNv4McgGqg7l42uELy4nOg6nCEhlFYX57e7rAZ9lzim4DBidoJnxPIC1DFIDiV248cw0bDj53LYj/9m08fHmBaNRFFkg06aLGgbgxcXZjtHmBedjChtkdabRtdERYnfIqNSRlw5tjD/YMtHIw+DlPayWUPdWlxRJtkLdvdUlyA0gyWEVGhLfgki/dgr8Syie5+H8IXusbb2PNKkdE+SOBb1beAH+UpN7AL4DWLYmYvW1gWUMHT1XYLYhU86FX9gnFRL9YkCz4OI6fo6neOuqM2CsVxohZJbQpBUMIJm1X1ixYejcoEGkoIWY1iG62Izyh4Q/MizxjI1mowbGPz96HHmGXy0pJ3LkpQ9KQmv7OW5ptDYN/b+Uq6nbJNdiU8rUpc43XGs41/jRFhDdbs6uJOdnAPv+pvHV+thPa3vOrnXTmNrFpDjHWStTZG7U9UqGeMaGf1wMysOfnEotPg3UJGLxPm7PsAwtyFAbBkFc=
  file: target/*.jar
  skip_cleanup: true
  on:
    repo: jbharter/Syndicate
    tags: true
