language: java

jdk:
  - openjdk8

branches:
  only:
  - develop
  - master

deploy:
  provider: releases
  api_key:
        secure: ja+KCPohVlfPRXwSWxq/MB56rYFtuGFBGPJXsMET22fFybwdSF7bXXZjKM9gJ2ITMxXBZAyI4C2QdUGMVaGOgEBCUZDKSWTQQgCwZ6muEWml2242U2G2lqr1bczA56mCxmyH0xmY/MUkpW3VH94FdTTW7uo6xkBeKXEflZnAS87ewDltBRE8E3104QdE70M+aFLIt6oNW6aA+//Cm/x4l92vGVd45e3dd+9sXV4E2BfINpEMOcfuAlnLFmr/JFdopkFqWVclTWMAt7vBzjUC5oI0pLwRfxpxr03fJyfv4R0e6vMgmNXUCURx8CKs6GBrRUTn/QMddaZdVdwjXALs2qZtu5WrkTqiquYHeDbQDzj91hTTs7QjvVHVLHfVdCePa/+zBx3v7Gnn9XTfXU++nGj3MmyjBW5eQoHTNtgSQzKkqAB4c/tiilKMvyHS7fYUu0nWl616x+u87ayG8mBrsg21FAybekINnRKeljCpQFvdgQu319s4H14MWb1pQyCTRfmHae3zS0eYGHEnvDJuE8AFh6mjG5+ezLsAKCjcQ86t+IXiJjcMbfWLnLwBAf1gWJxqst0xl0MJ995loqSDLEOTdSRRYLg+2tKTb8OAcUfy39tOZo8VdVBkSfoN9GfMV4gesaHUoiQCvf6OgRoAZURm4ggZEz9RiXqXyITggK0=
  file: "target/*.jar"
  skip_cleanup: true
  on:
    tags: true

